DELETE http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiYmFzMUBnbWFpbC5jb20iLCJleHAiOjE3NzQ3ODA2NDAsInVzZXJJZCI6MX0.rwld4FvZJ-y5xoU0MGtO-lueMzu__lcvdDYLmq2gbJc