DELETE http://localhost:8080/events/9
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiYmFzMUBnbWFpbC5jb20iLCJleHAiOjE3NzQ3NzUxNDIsInVzZXJJZCI6M30.mhxQDIH2CSvdfa_7aEvxkRBABGCeLCfUOGZmp0ucEsA