PUT http://localhost:8080/events/9
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiYmFzMUBnbWFpbC5jb20iLCJleHAiOjE3NzQ3NzUxNDIsInVzZXJJZCI6M30.mhxQDIH2CSvdfa_7aEvxkRBABGCeLCfUOGZmp0ucEsA

{
    "name":"Test (updated)",
    "description":"Description (updated)",
    "location":"Still Minia",
    "dateTime":"2026-04-02T15:30:00.000Z"
}